name: linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: luacheck
        uses: nebularg/actions-luacheck@v1.1.
      - name: python-lint
        uses: jpetrucciani/mypy-check@master
        with:
          mypy_flags: "--install-types --non-interactive"
